
title: "SajivSpeak"
email: sajiv3@gmail.com
description: >- 
  Exploring Law, AI, Gita, and Self-Mastery through AMAR.
baseurl: ""
url: "https://blog.sajivkumar.in"
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-seo-tag
markdown: kramdown
